import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from 'next-themes'

const inter = Inter({
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Bee Ai - Chat with bee Build with bee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
        attribute={"class"}
        defaultTheme="dark"
        >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
